# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17v8tl-mnmBV5kEZuaCfpyZ3PFIUjDdnJ
"""

import streamlit as st
import joblib
import numpy as np

st.title("Application Machine Learning")

model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

age = st.number_input("Âge")
balance = st.number_input("Solde")
salary = st.number_input("Salaire")

if st.button("Prédire"):
    X = np.array([[age, balance, salary]])
    X = scaler.transform(X)
    pred = model.predict(X)
    st.success(f"Cluster : {pred[0]}")